version: "3"
services:
  #SQL
  mysql:
    image: "mysql"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: netflix
      MYSQL_ROOT_PASSWORD: "password123"
    volumes: 
      - ~/Documents/nflix/sql:/var/lib/mysql

  #mongo
  mymongo:
    image: mongo
    restart: always
    ports: 
      - 9000:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes: 
      - ~/Documents/nflix/mongo:/data/db
  
  # flask
  flask:
    image: flask
    restart: always
    ports:
      - 5000:5000
    volumes: 
      - /home/stubuntu/Documents/GitHub_repos/netflix-clone/backend:/app


